# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Punch List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Punch List
	pod 'Firebase/Core'
  	pod ‘Firebase/Firestore’
  target 'Punch ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Punch ListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
