# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bucket List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
pod ‘Firebase/Auth’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Database’
  # Pods for Bucket List

  target 'Bucket ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bucket ListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
